/* Generated By:JJTree: Do not edit this line. ASTLogicalNegationExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=progen.Entity,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package minijavaparser;

public
class ASTLogicalNegationExpression extends progen.ProgenNode {
  public ASTLogicalNegationExpression(int id) {
    super(id);
  }

  public ASTLogicalNegationExpression(MiniJava p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c9eb882eb812f2b37c37e4b37962b1aa (do not edit this line) */
