/* Generated By:JJTree: Do not edit this line. ASTNewExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=progen.Entity,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package minijavaparser;

public class ASTNewExpression extends progen.ProgenNode {
	public String className;
	
	public ASTNewExpression(int id) {
		super(id);
	}

	public ASTNewExpression(MiniJava p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(MiniJavaVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=2984869ef8bab7edab0615351b39eead (do not edit this
 * line)
 */
