/* Generated By:JJTree: Do not edit this line. ASTPrimaryExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=progen.Entity,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package minijavaparser;

public
class ASTPrimaryExpr extends progen.ProgenNode {
  public ASTPrimaryExpr(int id) {
    super(id);
  }

  public ASTPrimaryExpr(MiniJava p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=75c7d8d13dd4ad851011d64c803df1b1 (do not edit this line) */
