/* Generated By:JJTree: Do not edit this line. ASTVariableDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=progen.Entity,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package minijavaparser;

public
class ASTVariableDeclaration extends progen.ProgenNode {
  public ASTVariableDeclaration(int id) {
    super(id);
  }

  public ASTVariableDeclaration(MiniJava p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=de39e6011f231b8dd6ac64fc3774314c (do not edit this line) */
